### ISSUE TITLE
Dėl pradinių/statinių duomenų

### ISSUE THREAD

**Issue by aidiss** [aidiss/opendatagovlt#12]
Projekte didžiąją dalį duomenų gausime iš šaltinių. Tačiau, dalį jų turėsime įvesti iš anksto. Tarp pradinių/statinių duomenų vardinčiau tokius akivaizdžius duomenis kaip opendatagovlt puslapį, duomenų tipus ir t.t. Bet yra keletas duomenų, kurie nėra tokie akivaizdūs.

Mano mažame eksperimente apie opendatagovlt naudojamą meta duomenų aprašymą rasta, kad ten duomenys aprašomi naudojam pasikartojančius tagus. Taigi, yra variantas, kad mes tuos tagus išsaugome, ir tada nesijaudiname, automatiniu jų atpažinimu.

Tokia prieiga leistų greičiau įgyvendinti projektą. Aišku, paslauga taptų ne tokia dinamiška, odgl puslapiui pradėjus naudoti kitus tagus reikėtų prie jų prisiderinti. Bet, manau, greitu metu jų praktikos nesikeis.

Lauksiu tavo pastebėjimų apie pradinių/statinių duomenų naudojimą.

**Comment by sirex** [comment]
Galė galėtum pavyzdžius ar nuorodas tų statinių duomenų? Nesu tikras ar supratau apie ką kalbi.

**Comment by aidiss** [comment]
Pavyzdžių daug neturiu, čia labiau filosofiškai žvelgiant... Pabandysiu tiksliau apibrėžti (gali būti, kad visiškai nesamones čia kalbu).

Botams pradėjus veikla bus generuojama daug lentelių, žodynų, sąrašų, tuple'ų ir t.t. Tačiau, iki projekto paleidimo mes turime daug ką surašyti, kad duomenų gavyba gerai veiktų.

Teoriškai matau tokius duomenis:
a) niekada nekinantys, įvesti rankiniu būdu - projekto kūrimo metu mes juos įvedame, jie nėra gaunami automatiškai. 
b) vieną kartą sukuriami - tarkime, naujo šaltinio ar temos sukūrimas
c) atnaujinami - duomenys, kurie dažnai keisis. Manau, kad tokių duomenų nebus daug. Bet gal galime juos iš anksto identifikuoti?

Jei mano sapalionės makes no sense tai galime trinti šią diskusiją lauk.

**Comment by sirex** [comment]
Gal būt čia kalbi ne apie statinius duomenis, o priešingai apie dinaminius, t.y. apie vidinę projekto duomenų bazės struktūrą? Ar teisingai supratau?

**Comment by aidiss** [comment]
Labiau apie sistemos konfigūraciją, pvz.:
kiek dažnai botas lankys puslapius, tai mes turėsime patys nustatyti.

Aš tai vadinu statiniais duomenimis, kadangi jie nekinta. Jų vertes nustatome iš anksto ir projekto eigoje vertės išlieka tomis pačiomis.
Nežinau, kiek vertinga ši diskusija, manau galime uždaryti :)

**Comment by sirex** [comment]
Dėl to, kiek dažnai robotas lankysis puslapyje bus aprašyta roboto instrukcijų faile. Tai ko gero, tie statiniai duomenys ir yra roboto instrukcijų failai.

Ok, tada uždarau šią diskusiją, nes greičiausiai bent dalį statinių duomenų saugosime roboto instrukcijų failuose.
